#include "../ShaderBindings.hlsli"

PRISM_VK_BINDING(0) cbuffer FluidRenderConstants : register(b0)
{
    float4x4 fluidView;
    float4x4 fluidProjection;
    float4x4 fluidInverseProjection;
    float4x4 fluidInverseView;
    float4 fluidResolutionInverseResolution;
    float4 fluidCameraPositionParticleRadius;
    float4 fluidFilterParameters;
    float4 fluidDensityParameters;
    float4 fluidAbsorptionScattering;
    float4 fluidWaterColorIor;
    float4 fluidOpticalParameters;
    float4 fluidFoamParameters;
    float4 fluidToonParameters;
    float4 fluidLightDirectionOutline;
    uint4 fluidCountsAndModes;
};

PRISM_VK_BINDING(16)
StructuredBuffer<float4> particlePositions : register(t0);
PRISM_VK_BINDING(17)
Texture2D<float> sceneDepthTexture : register(t1);
PRISM_VK_BINDING(18)
StructuredBuffer<float> particleDensities : register(t2);

#define fluidResolution fluidResolutionInverseResolution.xy
#define fluidParticleRadius fluidCameraPositionParticleRadius.w
#define fluidMinimumDensityRatio fluidDensityParameters.x
#define fluidFoamDensityRatio fluidDensityParameters.y
#define fluidDensityAvailable fluidDensityParameters.z

struct ParticleVertexOutput
{
    float4 position : SV_POSITION;
    float2 corner : TEXCOORD0;
    float3 centerView : TEXCOORD1;
    nointerpolation float densityRatio : TEXCOORD2;
};

static const float2 ParticleQuadCorners[6] =
{
    float2(-1.0f, -1.0f),
    float2(-1.0f,  1.0f),
    float2( 1.0f,  1.0f),
    float2(-1.0f, -1.0f),
    float2( 1.0f,  1.0f),
    float2( 1.0f, -1.0f)
};

ParticleVertexOutput ParticleBillboardVS(
    uint vertexId : SV_VertexID,
    uint instanceId : SV_InstanceID)
{
    ParticleVertexOutput output;
    const float2 corner = ParticleQuadCorners[vertexId % 6u];
    const float encodedDensity = fluidDensityAvailable > 0.5f
        ? particleDensities[instanceId]
        : 1.0f;
    const float densityRatio = abs(encodedDensity);
    const bool isolatedDynamicSpray = encodedDensity < 0.0f;
    if (isolatedDynamicSpray
        || densityRatio < fluidMinimumDensityRatio)
    {
        // Collapse culled particles before rasterization.  This avoids the
        // expensive sphere fragments generated by isolated spray particles.
        output.position = float4(2.0f, 2.0f, 2.0f, 1.0f);
        output.corner = 0.0f.xx;
        output.centerView = 0.0f.xxx;
        output.densityRatio = densityRatio;
        return output;
    }
    const float3 worldCenter = particlePositions[instanceId].xyz;
    const float3 centerView = mul(
        float4(worldCenter, 1.0f), fluidView).xyz;
    const float3 vertexView = centerView
        + float3(corner * fluidParticleRadius, 0.0f);
    output.position = mul(
        float4(vertexView, 1.0f), fluidProjection);
    output.corner = corner;
    output.centerView = centerView;
    output.densityRatio = densityRatio;
    return output;
}

bool ComputeSphereSurface(
    ParticleVertexOutput input,
    out float3 surfaceView,
    out float deviceDepth,
    out float chordLength)
{
    const float radiusSquared = dot(input.corner, input.corner);
    if (radiusSquared > 1.0f
        || input.centerView.z <= fluidParticleRadius)
    {
        surfaceView = 0.0f.xxx;
        deviceDepth = 1.0f;
        chordLength = 0.0f;
        return false;
    }

    const float sphereZ = sqrt(max(1.0f - radiusSquared, 0.0f));
    surfaceView = input.centerView
        + float3(
            input.corner * fluidParticleRadius,
            -sphereZ * fluidParticleRadius);
    const float4 surfaceClip = mul(
        float4(surfaceView, 1.0f), fluidProjection);
    if (surfaceClip.w <= 0.00001f)
    {
        deviceDepth = 1.0f;
        chordLength = 0.0f;
        return false;
    }
    deviceDepth = surfaceClip.z / surfaceClip.w;
    chordLength = 2.0f * sphereZ * fluidParticleRadius;
    return deviceDepth > 0.0f && deviceDepth < 1.0f;
}

bool IsOccludedByScene(
    float4 rasterPosition,
    float deviceDepth)
{
    const uint2 pixel = min(
        uint2(rasterPosition.xy),
        uint2(fluidResolution) - 1u);
    const float sceneDepth = sceneDepthTexture.Load(
        int3(pixel, 0));
    return deviceDepth >= sceneDepth - 1.0e-6f;
}

struct ParticleDepthOutput
{
    float linearDepth : SV_TARGET0;
    float mask : SV_TARGET1;
    float deviceDepth : SV_DEPTH;
};

ParticleDepthOutput ParticleDepthPS(
    ParticleVertexOutput input)
{
    ParticleDepthOutput output;
    float3 surfaceView = 0.0f.xxx;
    float deviceDepth = 1.0f;
    float chordLength = 0.0f;
    if (!ComputeSphereSurface(
            input,
            surfaceView,
            deviceDepth,
            chordLength)
        || IsOccludedByScene(input.position, deviceDepth))
    {
        discard;
    }
    output.linearDepth = surfaceView.z;
    // The mask remains > 0.5 for every valid fluid pixel.  0.75 encodes the
    // low-density interval used by the optional foam morphology pass.
    output.mask = input.densityRatio <= fluidFoamDensityRatio
        ? 0.75f
        : 1.0f;
    output.deviceDepth = deviceDepth;
    return output;
}

float ParticleThicknessPS(
    ParticleVertexOutput input) : SV_TARGET0
{
    float3 surfaceView = 0.0f.xxx;
    float deviceDepth = 1.0f;
    float chordLength = 0.0f;
    if (!ComputeSphereSurface(
            input,
            surfaceView,
            deviceDepth,
            chordLength)
        || IsOccludedByScene(input.position, deviceDepth))
    {
        discard;
    }
    return chordLength;
}
