include_guard(GLOBAL)

function(_prism_boundary_glob_matches output path pattern)
    file(TO_CMAKE_PATH "${path}" normalized_path)
    file(TO_CMAKE_PATH "${pattern}" normalized_pattern)
    string(REPLACE "." "\\." regex "${normalized_pattern}")
    string(REPLACE "**/" "@PRISM_DIR@" regex "${regex}")
    string(REPLACE "**" "@PRISM_ALL@" regex "${regex}")
    string(REPLACE "*" "[^/]*" regex "${regex}")
    string(REPLACE "?" "[^/]" regex "${regex}")
    string(REPLACE "@PRISM_DIR@" "(.*/)?" regex "${regex}")
    string(REPLACE "@PRISM_ALL@" ".*" regex "${regex}")
    if(normalized_path MATCHES "^${regex}$")
        set(${output} TRUE PARENT_SCOPE)
    else()
        set(${output} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_prism_boundary_json_array output json)
    string(JSON length ERROR_VARIABLE error LENGTH "${json}" ${ARGN})
    if(NOT error STREQUAL "NOTFOUND")
        set(${output} "" PARENT_SCOPE)
        return()
    endif()
    set(values "")
    if(length GREATER 0)
        math(EXPR last "${length} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON value GET "${json}" ${ARGN} ${index})
            list(APPEND values "${value}")
        endforeach()
    endif()
    set(${output} "${values}" PARENT_SCOPE)
endfunction()

function(_prism_boundary_json_object_lookup output_found output_value json object_name member_name)
    string(JSON length ERROR_VARIABLE error LENGTH "${json}" "${object_name}")
    if(NOT error STREQUAL "NOTFOUND")
        set(${output_found} FALSE PARENT_SCOPE)
        set(${output_value} "" PARENT_SCOPE)
        return()
    endif()
    if(length GREATER 0)
        math(EXPR last "${length} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON key MEMBER "${json}" "${object_name}" ${index})
            if(key STREQUAL member_name)
                string(JSON value GET "${json}" "${object_name}" "${key}")
                set(${output_found} TRUE PARENT_SCOPE)
                set(${output_value} "${value}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endif()
    set(${output_found} FALSE PARENT_SCOPE)
    set(${output_value} "" PARENT_SCOPE)
endfunction()

function(_prism_boundary_any_rule_matches output path)
    set(matched FALSE)
    foreach(pattern IN LISTS ARGN)
        _prism_boundary_glob_matches(rule_matched "${path}" "${pattern}")
        if(rule_matched)
            set(matched TRUE)
            break()
        endif()
    endforeach()
    set(${output} ${matched} PARENT_SCOPE)
endfunction()

function(_prism_boundary_module_index output json target)
    string(JSON count LENGTH "${json}" modules)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON candidate GET "${json}" modules ${index} target)
            if(candidate STREQUAL target)
                set(${output} ${index} PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endif()
    set(${output} -1 PARENT_SCOPE)
endfunction()

function(_prism_boundary_path_owner output_owner output_visibility json path kind)
    _prism_boundary_json_object_lookup(
        has_entry entry_owner "${json}" executableEntryPoints "${path}")
    if(kind STREQUAL "source" AND has_entry)
        set(${output_owner} "${entry_owner}" PARENT_SCOPE)
        set(${output_visibility} "entrypoint" PARENT_SCOPE)
        return()
    endif()

    _prism_boundary_json_object_lookup(
        has_override override_owner "${json}" explicitPathOwnership "${path}")
    string(JSON module_count LENGTH "${json}" modules)
    set(owners "")
    set(visibility "")
    if(module_count GREATER 0)
        math(EXPR module_last "${module_count} - 1")
        foreach(module_index RANGE 0 ${module_last})
            string(JSON target GET "${json}" modules ${module_index} target)
            if(has_override AND NOT target STREQUAL override_owner)
                continue()
            endif()
            if(kind STREQUAL "source")
                _prism_boundary_json_array(
                    rules "${json}" modules ${module_index} sourceRules)
                _prism_boundary_json_array(
                    exclusions "${json}" modules ${module_index} sourceExclusions)
                _prism_boundary_any_rule_matches(included "${path}" ${rules})
                _prism_boundary_any_rule_matches(excluded "${path}" ${exclusions})
                if(included AND NOT excluded)
                    list(APPEND owners "${target}")
                endif()
            else()
                _prism_boundary_json_array(
                    public_rules "${json}" modules ${module_index} publicHeaders)
                _prism_boundary_json_array(
                    internal_rules "${json}" modules ${module_index} internalHeaders)
                _prism_boundary_any_rule_matches(is_public "${path}" ${public_rules})
                _prism_boundary_any_rule_matches(is_internal "${path}" ${internal_rules})
                if(is_public OR is_internal)
                    list(APPEND owners "${target}")
                    if(is_public)
                        set(visibility "public")
                    else()
                        set(visibility "internal")
                    endif()
                endif()
            endif()
        endforeach()
    endif()
    list(REMOVE_DUPLICATES owners)
    set(${output_owner} "${owners}" PARENT_SCOPE)
    set(${output_visibility} "${visibility}" PARENT_SCOPE)
endfunction()

function(_prism_boundary_declared_dependencies output json target)
    _prism_boundary_module_index(module_index "${json}" "${target}")
    if(module_index LESS 0)
        set(${output} "" PARENT_SCOPE)
        return()
    endif()
    _prism_boundary_json_array(
        dependencies "${json}" modules ${module_index} directDependencies)
    string(JSON condition_count ERROR_VARIABLE condition_error
        LENGTH "${json}" modules ${module_index} conditionalDependencies)
    if(condition_error STREQUAL "NOTFOUND" AND condition_count GREATER 0)
        math(EXPR condition_last "${condition_count} - 1")
        foreach(condition_index RANGE 0 ${condition_last})
            string(JSON condition MEMBER "${json}"
                modules ${module_index} conditionalDependencies ${condition_index})
            _prism_boundary_json_array(condition_dependencies "${json}"
                modules ${module_index} conditionalDependencies "${condition}")
            list(APPEND dependencies ${condition_dependencies})
        endforeach()
    endif()
    list(REMOVE_DUPLICATES dependencies)
    set(${output} "${dependencies}" PARENT_SCOPE)
endfunction()

function(_prism_boundary_internal_include_allowed output json consumer provider source_path header_path)
    string(JSON count ERROR_VARIABLE error LENGTH "${json}" allowedInternalHeaderIncludes)
    if(NOT error STREQUAL "NOTFOUND")
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON allowed_consumer GET "${json}" allowedInternalHeaderIncludes ${index} consumer)
            string(JSON allowed_provider GET "${json}" allowedInternalHeaderIncludes ${index} provider)
            if(NOT allowed_consumer STREQUAL consumer OR NOT allowed_provider STREQUAL provider)
                continue()
            endif()
            _prism_boundary_json_array(source_rules "${json}" allowedInternalHeaderIncludes ${index} sourceRules)
            _prism_boundary_json_array(header_rules "${json}" allowedInternalHeaderIncludes ${index} headerRules)
            _prism_boundary_any_rule_matches(source_matches "${source_path}" ${source_rules})
            _prism_boundary_any_rule_matches(header_matches "${header_path}" ${header_rules})
            if(source_matches AND header_matches)
                set(${output} TRUE PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endif()
    set(${output} FALSE PARENT_SCOPE)
endfunction()

function(_prism_boundary_test_recompile_allowed output json target source_path)
    string(JSON count ERROR_VARIABLE error LENGTH "${json}" allowedTestRecompilation)
    if(NOT error STREQUAL "NOTFOUND")
        set(${output} FALSE PARENT_SCOPE)
        return()
    endif()
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            _prism_boundary_json_array(targets "${json}" allowedTestRecompilation ${index} targets)
            if(NOT target IN_LIST targets)
                continue()
            endif()
            _prism_boundary_json_array(rules "${json}" allowedTestRecompilation ${index} sourceRules)
            _prism_boundary_any_rule_matches(matches "${source_path}" ${rules})
            if(matches)
                set(${output} TRUE PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endif()
    set(${output} FALSE PARENT_SCOPE)
endfunction()

function(prism_check_module_boundaries)
    cmake_parse_arguments(PARSE_ARGV 0 argument "" "MANIFEST;ROOT" "TARGETS")
    if(NOT argument_MANIFEST OR NOT argument_ROOT)
        message(FATAL_ERROR "prism_check_module_boundaries requires MANIFEST and ROOT.")
    endif()
    get_filename_component(root "${argument_ROOT}" ABSOLUTE)
    file(READ "${argument_MANIFEST}" manifest)
    set(errors "")

    string(JSON module_count LENGTH "${manifest}" modules)
    set(module_targets "")
    if(module_count GREATER 0)
        math(EXPR module_last "${module_count} - 1")
        foreach(module_index RANGE 0 ${module_last})
            string(JSON module_target GET "${manifest}" modules ${module_index} target)
            list(APPEND module_targets "${module_target}")
        endforeach()
    endif()

    file(GLOB_RECURSE production_sources LIST_DIRECTORIES FALSE
        "${root}/src/*.cpp" "${root}/src/*.c")
    file(GLOB_RECURSE project_headers LIST_DIRECTORIES FALSE
        "${root}/src/*.h" "${root}/src/*.hpp")
    set(owned_paths "")
    foreach(source IN LISTS production_sources)
        file(RELATIVE_PATH relative "${root}" "${source}")
        file(TO_CMAKE_PATH "${relative}" relative)
        _prism_boundary_path_owner(owner visibility "${manifest}" "${relative}" source)
        list(LENGTH owner owner_count)
        if(NOT owner_count EQUAL 1)
            list(APPEND errors
                "source ownership ${relative}: expected exactly one owner, found [${owner}]")
        else()
            list(APPEND owned_paths "${relative}|${owner}")
        endif()
    endforeach()

    foreach(header IN LISTS project_headers)
        file(RELATIVE_PATH relative "${root}" "${header}")
        file(TO_CMAKE_PATH "${relative}" relative)
        _prism_boundary_path_owner(owner visibility "${manifest}" "${relative}" header)
        list(LENGTH owner owner_count)
        if(NOT owner_count EQUAL 1)
            list(APPEND errors
                "header ownership ${relative}: expected exactly one owner, found [${owner}]")
        endif()
    endforeach()

    foreach(path IN LISTS production_sources project_headers)
        file(RELATIVE_PATH relative "${root}" "${path}")
        file(TO_CMAKE_PATH "${relative}" relative)
        if(relative MATCHES "\\.(cpp|c)$")
            _prism_boundary_path_owner(consumer consumer_visibility "${manifest}" "${relative}" source)
        else()
            _prism_boundary_path_owner(consumer consumer_visibility "${manifest}" "${relative}" header)
        endif()
        list(LENGTH consumer consumer_count)
        if(NOT consumer_count EQUAL 1 OR consumer_visibility STREQUAL "entrypoint")
            continue()
        endif()
        file(STRINGS "${path}" include_lines
            REGEX "^[ \t]*#[ \t]*include[ \t]*\"[^\"]+\"")
        foreach(include_line IN LISTS include_lines)
            string(REGEX REPLACE
                "^[ \t]*#[ \t]*include[ \t]*\"([^\"]+)\".*$" "\\1"
                include_path "${include_line}")
            if(NOT EXISTS "${root}/src/${include_path}")
                continue()
            endif()
            set(header_relative "src/${include_path}")
            _prism_boundary_path_owner(provider provider_visibility
                "${manifest}" "${header_relative}" header)
            list(LENGTH provider provider_count)
            if(NOT provider_count EQUAL 1 OR provider STREQUAL consumer)
                continue()
            endif()
            if(provider_visibility STREQUAL "internal")
                _prism_boundary_internal_include_allowed(
                    internal_allowed "${manifest}" "${consumer}" "${provider}"
                    "${relative}" "${header_relative}")
                if(NOT internal_allowed)
                    list(APPEND errors
                        "internal header boundary ${consumer} -> ${provider}: ${relative} includes ${header_relative}")
                endif()
            endif()
            _prism_boundary_declared_dependencies(
                declared_dependencies "${manifest}" "${consumer}")
            if(NOT provider IN_LIST declared_dependencies)
                list(APPEND errors
                    "missing direct dependency ${consumer} -> ${provider}: ${relative} includes ${header_relative}")
            endif()
        endforeach()
    endforeach()

    if(argument_TARGETS)
        set(targets ${argument_TARGETS})
    else()
        get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
    endif()
    set(graph_edges "")
    foreach(target IN LISTS targets)
        if(NOT TARGET "${target}")
            continue()
        endif()
        get_target_property(target_sources "${target}" SOURCES)
        if(target_sources AND NOT target_sources STREQUAL "target_sources-NOTFOUND")
            set(all_target_sources ${target_sources})
        else()
            set(all_target_sources "")
        endif()
        get_target_property(interface_sources "${target}" INTERFACE_SOURCES)
        if(interface_sources AND NOT interface_sources STREQUAL "interface_sources-NOTFOUND")
            list(APPEND all_target_sources ${interface_sources})
        endif()
        if(all_target_sources)
            foreach(source IN LISTS all_target_sources)
                if(source MATCHES "^\\$<")
                    continue()
                endif()
                get_filename_component(source_absolute "${source}" ABSOLUTE BASE_DIR "${root}")
                file(RELATIVE_PATH relative "${root}" "${source_absolute}")
                file(TO_CMAKE_PATH "${relative}" relative)
                if(NOT relative MATCHES "^src/.*\\.(cpp|c)$")
                    continue()
                endif()
                _prism_boundary_path_owner(owner visibility "${manifest}" "${relative}" source)
                list(LENGTH owner owner_count)
                if(NOT owner_count EQUAL 1 OR target STREQUAL owner)
                    continue()
                endif()
                _prism_boundary_test_recompile_allowed(
                    allowed "${manifest}" "${target}" "${relative}")
                if(NOT allowed)
                    list(APPEND errors
                        "undeclared source recompilation ${relative}: owner ${owner}, target ${target}")
                endif()
            endforeach()
        endif()

        if(NOT target IN_LIST module_targets)
            continue()
        endif()
        _prism_boundary_declared_dependencies(
            declared_dependencies "${manifest}" "${target}")
        get_target_property(link_libraries "${target}" LINK_LIBRARIES)
        if(NOT link_libraries OR link_libraries STREQUAL "link_libraries-NOTFOUND")
            set(link_libraries "")
        endif()
        get_target_property(interface_link_libraries "${target}" INTERFACE_LINK_LIBRARIES)
        if(interface_link_libraries AND
           NOT interface_link_libraries STREQUAL "interface_link_libraries-NOTFOUND")
            list(APPEND link_libraries ${interface_link_libraries})
        endif()
        set(actual_module_dependencies "")
        foreach(dependency IN LISTS link_libraries)
            if(dependency MATCHES "^\\$<LINK_ONLY:([^>]+)>$")
                set(dependency "${CMAKE_MATCH_1}")
            endif()
            if(dependency IN_LIST module_targets)
                list(APPEND actual_module_dependencies "${dependency}")
            endif()
        endforeach()
        list(REMOVE_DUPLICATES actual_module_dependencies)
        foreach(dependency IN LISTS actual_module_dependencies)
            if(NOT dependency IN_LIST declared_dependencies)
                list(APPEND errors
                    "undeclared target edge ${target} -> ${dependency}")
            endif()
            list(APPEND graph_edges "${target}|${dependency}")
        endforeach()
        foreach(dependency IN LISTS declared_dependencies)
            if(TARGET "${dependency}" AND NOT dependency IN_LIST actual_module_dependencies)
                list(APPEND errors
                    "missing target edge ${target} -> ${dependency}")
            endif()
        endforeach()
    endforeach()

    string(JSON forbidden_count ERROR_VARIABLE forbidden_error
        LENGTH "${manifest}" forbiddenDirectEdges)
    if(forbidden_error STREQUAL "NOTFOUND" AND forbidden_count GREATER 0)
        math(EXPR forbidden_last "${forbidden_count} - 1")
        foreach(forbidden_index RANGE 0 ${forbidden_last})
            string(JSON forbidden_from GET "${manifest}"
                forbiddenDirectEdges ${forbidden_index} 0)
            string(JSON forbidden_to GET "${manifest}"
                forbiddenDirectEdges ${forbidden_index} 1)
            if("${forbidden_from}|${forbidden_to}" IN_LIST graph_edges)
                list(APPEND errors
                    "forbidden target edge ${forbidden_from} -> ${forbidden_to}")
            endif()
        endforeach()
    endif()

    set(reachability ${graph_edges})
    foreach(iteration RANGE 0 ${module_count})
        set(snapshot ${reachability})
        foreach(left IN LISTS snapshot)
            string(REPLACE "|" ";" left_parts "${left}")
            list(GET left_parts 0 left_from)
            list(GET left_parts 1 left_to)
            foreach(right IN LISTS snapshot)
                string(REPLACE "|" ";" right_parts "${right}")
                list(GET right_parts 0 right_from)
                list(GET right_parts 1 right_to)
                if(left_to STREQUAL right_from)
                    list(APPEND reachability "${left_from}|${right_to}")
                endif()
            endforeach()
        endforeach()
        list(REMOVE_DUPLICATES reachability)
    endforeach()
    foreach(target IN LISTS module_targets)
        if("${target}|${target}" IN_LIST reachability)
            list(APPEND errors "target cycle reaches ${target}")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES errors)
    list(LENGTH errors error_count)
    if(error_count GREATER 0)
        list(JOIN errors "\n  - " error_text)
        message(FATAL_ERROR
            "Prism module boundary validation failed (${error_count}):\n  - ${error_text}")
    endif()
    list(LENGTH production_sources production_source_count)
    message(STATUS
        "Prism module boundaries passed: ${module_count} modules, ${production_source_count} production sources checked.")
endfunction()
