set(PRISM_RENDERER_SOURCES
    src/Renderer/Frustum.cpp
    src/Renderer/Features/ClusteredLighting.cpp
    src/Renderer/DemoSceneSettings.cpp
    src/Renderer/Features/GpuDrivenVisibility.cpp
    src/Renderer/Features/FftOcean.cpp
    src/Renderer/Features/Ocean/OceanFeature.cpp
    src/Renderer/Features/Ocean/OceanSettings.cpp
    src/Renderer/Features/Ocean/WaterOpticsHistory.cpp
    src/Renderer/Features/Ocean/WaterCaustics.cpp
    src/Renderer/Features/Ocean/WaterMediumState.cpp
    src/Renderer/Features/Ocean/WaterVolumetricHistory.cpp
    src/Renderer/Features/Ocean/WaterCoverageReadback.cpp
    src/Renderer/Features/Ocean/WaterBenchmarkReport.cpp
    src/Renderer/Features/Ocean/WaterOpticsSettings.cpp
    src/Renderer/Features/Ocean/WaterRefractionModel.cpp
    src/Renderer/Features/Ocean/WaterOpticalModel.cpp
    src/Renderer/Features/Ocean/WaterOpticsTransientLayout.cpp
    src/Renderer/Features/Ocean/OceanSpectrumMath.cpp
    src/Renderer/Features/Ocean/SpectralOceanSimulation.cpp
    src/Renderer/Features/Ocean/OceanFallbackResources.cpp
    src/Renderer/Features/Ocean/OceanSpectrumGenerator.cpp
    src/Renderer/Features/Ocean/OceanFft.cpp
    src/Renderer/Features/Ocean/OceanFftGpu.cpp
    src/Renderer/Features/Ocean/OceanMapBuilder.cpp
    src/Renderer/Features/Ocean/OceanFoamSimulation.cpp
    src/Renderer/Features/Ocean/LocalWaveSimulation.cpp
    src/Renderer/Features/Ocean/LocalWaveGpuResources.cpp
    src/Renderer/Features/Ocean/WaterOpticsFeature.cpp
    src/Renderer/Features/Ocean/OceanSurfaceRenderer.cpp
    src/Renderer/Features/Ocean/OceanQuadtree.cpp
    src/Renderer/Features/Ocean/OceanQueryService.cpp
    src/Renderer/Features/Ocean/OceanGpuQuery.cpp
    src/Renderer/Features/InteractiveTerrain.cpp
    src/Renderer/Features/Fluid/FluidCaustics.cpp
    src/Renderer/Features/Fluid/FluidFeature.cpp
    src/Renderer/Features/Fluid/PbfFluidSimulation.cpp
    src/Renderer/Features/Fluid/ScreenSpaceFluidRenderer.cpp
    src/Renderer/Features/BuiltInRenderFeatures.cpp
    src/Renderer/DeferredTransientLayout.cpp
    src/Renderer/Features/LocalLightShadows.cpp
    src/Renderer/MaterialParameterResolver.cpp
    src/Renderer/Features/PlanarReflections.cpp
    src/Renderer/GpuTimingReport.cpp
    src/Renderer/PerformanceIdentity.cpp
    src/Renderer/Pipeline/PipelineCache.cpp
    src/Renderer/Pipeline/ScenePipelinePlan.cpp
    src/Renderer/QueueSchedulingCostModel.cpp
    src/Renderer/RenderFeatureRegistry.cpp
    src/Renderer/Graph/GraphCompiler.cpp
    src/Renderer/Graph/GraphExecutor.cpp
    src/Renderer/Graph/QueueScheduler.cpp
    src/Renderer/Graph/ResourceLifetimePlanner.cpp
    src/Renderer/Graph/ResourceStateTracker.cpp
    src/Renderer/Graph/TransientAliasPlanner.cpp
    src/Renderer/RenderGraph.cpp
    src/Renderer/RenderGraphCompiler.cpp
    src/Renderer/RenderGraphResources.cpp
    src/Renderer/RenderGraphDiagnostics.cpp
    src/Renderer/FrameDiagnostics.cpp
    src/Renderer/RenderFrameCoordinator.cpp
    src/Renderer/RenderHistorySettingsTracker.cpp
    src/Renderer/SceneRendererDiagnostics.cpp
    src/Renderer/SharedRenderGraphFrontend.cpp
    src/Renderer/Features/ScreenSpaceEffects.cpp
    src/Renderer/Features/SkyAtmosphere.cpp
    src/Renderer/SceneRenderer.cpp
    src/Renderer/SceneRendererSharedResources.cpp
    src/Renderer/SceneRendererPasses.cpp
    src/Renderer/SceneRendererPipeline.cpp
    src/Renderer/SceneRendererResources.cpp
    src/Renderer/Features/TemporalAntiAliasing.cpp
    src/Renderer/Features/VirtualTextureCache.cpp
    src/Renderer/Features/VarianceShadowMaps.cpp
    src/Renderer/RhiPasses.cpp
    src/Renderer/ShadowCascades.cpp
)

set(PRISM_RENDERER_HEADERS
    src/Renderer/Graph/CompiledGraph.h
    src/Renderer/Graph/GraphCompiler.h
    src/Renderer/Graph/GraphDescription.h
    src/Renderer/Graph/GraphExecutor.h
    src/Renderer/Graph/GraphExecutionState.h
    src/Renderer/Graph/QueueScheduler.h
    src/Renderer/Graph/ResourceLifetimePlanner.h
    src/Renderer/Graph/ResourceStateTracker.h
    src/Renderer/Graph/TransientAliasPlanner.h
    src/Renderer/Frustum.h
    src/Renderer/Features/ClusteredLighting.h
    src/Renderer/DemoSceneSettings.h
    src/Renderer/Features/GpuDrivenVisibility.h
    src/Renderer/Features/FftOcean.h
    src/Renderer/Features/Ocean/OceanSettings.h
    src/Renderer/Features/Ocean/OceanSpectrumMath.h
    src/Renderer/Features/Ocean/OceanStatistics.h
    src/Renderer/Features/Ocean/OceanFeature.h
    src/Renderer/Features/Ocean/WaterOpticsHistory.h
    src/Renderer/Features/Ocean/WaterCaustics.h
    src/Renderer/Features/Ocean/WaterMediumState.h
    src/Renderer/Features/Ocean/WaterVolumetricHistory.h
    src/Renderer/Features/Ocean/WaterOpticsFeature.h
    src/Renderer/Features/Ocean/WaterOpticsGraph.h
    src/Renderer/Features/Ocean/WaterRefractionModel.h
    src/Renderer/Features/Ocean/WaterOpticalModel.h
    src/Renderer/Features/Ocean/WaterOpticsSettings.h
    src/Renderer/Features/Ocean/WaterOpticsTransientLayout.h
    src/Renderer/Features/Ocean/SpectralOceanSimulation.h
    src/Renderer/Features/Ocean/OceanFallbackResources.h
    src/Renderer/Features/Ocean/OceanSpectrumGenerator.h
    src/Renderer/Features/Ocean/OceanFft.h
    src/Renderer/Features/Ocean/OceanMapBuilder.h
    src/Renderer/Features/Ocean/OceanFoamSimulation.h
    src/Renderer/Features/Ocean/LocalWaveSimulation.h
    src/Renderer/Features/Ocean/LocalWaveGpuResources.h
    src/Renderer/Features/Ocean/OceanSurfaceRenderer.h
    src/Renderer/Features/Ocean/OceanQuadtree.h
    src/Renderer/Features/Ocean/OceanQueryService.h
    src/Renderer/Features/Ocean/OceanGpuQuery.h
    src/Renderer/Features/InteractiveTerrain.h
    src/Renderer/Features/Fluid/FluidCaustics.h
    src/Renderer/Features/Fluid/FluidFeature.h
    src/Renderer/Features/Fluid/FluidGraph.h
    src/Renderer/Features/Fluid/FluidSettings.h
    src/Renderer/Features/Fluid/FluidStatistics.h
    src/Renderer/Features/Fluid/PbfFluidSimulation.h
    src/Renderer/Features/Fluid/ScreenSpaceFluidRenderer.h
    src/Renderer/DeferredTransientLayout.h
    src/Renderer/Features/BuiltInRenderFeatures.h
    src/Renderer/Features/FeatureGraphTypes.h
    src/Renderer/Features/LocalLightShadows.h
    src/Renderer/MaterialParameterResolver.h
    src/Renderer/Features/PlanarReflections.h
    src/Renderer/GpuTimingReport.h
    src/Renderer/PerformanceIdentity.h
    src/Renderer/Pipeline/PipelineCache.h
    src/Renderer/Pipeline/ScenePipelinePlan.h
    src/Renderer/QueueSchedulingCostModel.h
    src/Renderer/Features/RenderFeature.h
    src/Renderer/Features/RenderFeatureContext.h
    src/Renderer/RenderFeatureRegistry.h
    src/Renderer/RenderGraph.h
    src/Renderer/RenderGraphResources.h
    src/Renderer/RenderGraphDiagnostics.h
    src/Renderer/FrameDiagnostics.h
    src/Renderer/RenderFrameCoordinator.h
    src/Renderer/SharedRenderGraphFrontend.h
    src/Renderer/Features/ScreenSpaceEffects.h
    src/Renderer/Features/SkyAtmosphere.h
    src/Renderer/SceneRenderer.h
    src/Renderer/SceneRendererSharedResources.h
    src/Renderer/Features/TemporalAntiAliasing.h
    src/Renderer/Features/VirtualTextureCache.h
    src/Renderer/Features/VarianceShadowMaps.h
    src/Renderer/RhiPasses.h
    src/Renderer/RenderSettings.h
    src/Renderer/RenderHistorySettingsTracker.h
    src/Renderer/RenderCapture.h
    src/Renderer/SharedRenderData.h
    src/Renderer/ShadowCascades.h
    src/Renderer/RendererStatistics.h
)
