set(PRISM_SCENE_SOURCES
    src/Scene/AssetStreamingSceneBridge.cpp
    src/Scene/Camera.cpp
    src/Scene/CameraController.cpp
    src/Scene/DefaultSceneFactory.cpp
    src/Scene/DemoSceneBuilder.cpp
    src/Scene/DemoSceneCatalog.cpp
    src/Scene/FeatureLabSceneFactory.cpp
    src/Scene/FluidLabSceneFactory.cpp
    src/Scene/LightingShowcaseSceneFactory.cpp
    src/Scene/ProceduralErosionTerrain.cpp
    src/Scene/RenderDynamicInputState.cpp
    src/Scene/RenderFramePacket.cpp
    src/Scene/RenderScene.cpp
    src/Scene/RenderSceneData.cpp
    src/Scene/RenderSceneExtractionStatistics.cpp
    src/Scene/RenderSceneExtractor.cpp
    src/Scene/RenderSceneIdentity.cpp
    src/Scene/RenderSceneMailbox.cpp
    src/Scene/RenderSceneObjectMapping.cpp
    src/Scene/SceneFraming.cpp
    src/Scene/SceneLoader.cpp
    src/Scene/SceneSerializer.cpp
    src/Scene/SceneSession.cpp
    src/Scene/ShadowShowcaseSceneFactory.cpp
    src/Scene/ShowcaseSceneFactory.cpp
    src/Scene/TerrainOceanSceneFactory.cpp
    src/Scene/Transform.cpp
    src/Scene/WorldRenderSceneBridge.cpp
    src/Scene/WorldRenderSnapshot.cpp
)

set(PRISM_SCENE_HEADERS
    src/Scene/AssetStreamingSceneBridge.h
    src/Scene/Camera.h
    src/Scene/CameraController.h
    src/Scene/DefaultSceneFactory.h
    src/Scene/DemoSceneBuilder.h
    src/Scene/DemoSceneCatalog.h
    src/Scene/FeatureLabSceneFactory.h
    src/Scene/FluidLabSceneFactory.h
    src/Scene/Light.h
    src/Scene/LightingShowcaseSceneFactory.h
    src/Scene/ProceduralErosionTerrain.h
    src/Scene/RenderDynamicInputState.h
    src/Scene/RenderFramePacket.h
    src/Scene/RenderObject.h
    src/Scene/RenderScene.h
    src/Scene/RenderSceneAssetBindings.h
    src/Scene/RenderSceneData.h
    src/Scene/RenderSceneExtractionStatistics.h
    src/Scene/RenderSceneExtractor.h
    src/Scene/RenderSceneIdentity.h
    src/Scene/RenderSceneMailbox.h
    src/Scene/RenderSceneObjectMapping.h
    src/Scene/RenderSceneView.h
    src/Scene/RenderView.h
    src/Scene/RenderViewFeedback.h
    src/Scene/SceneFraming.h
    src/Scene/SceneLoader.h
    src/Scene/SceneSerializer.h
    src/Scene/SceneSession.h
    src/Scene/ShadowShowcaseSceneFactory.h
    src/Scene/ShowcaseSceneFactory.h
    src/Scene/TerrainOceanSceneFactory.h
    src/Scene/Transform.h
    src/Scene/WorldRenderSceneBridge.h
    src/Scene/WorldRenderSnapshot.h
)
